### ISSUE TITLE
Bezel Not appearing when Screen Effect is set

### ISSUE THREAD

**Issue by pofo14** [Duimon/Duimon-BigPEmu#3]
The shader aspect of these presets are working from for me in the emulator, however the outer "bezel" is not appearing it is just black bars.  I am on the latest version of the EMU - 1.094

**Comment by Duimon** [comment]
Make sure your "Video>>Screen Scaling" is set to "Stretch".

**Comment by pofo14** [comment]
> Make sure your "Video>>Screen Scaling" is set to "Stretch".

That did the trick.  Thanks

**Comment by pofo14** [comment]
Closed
